# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c4af52451439bfd007aec7d1caf4f284846d70528f3a3f73a066ed32fb56e9dccb9f734a16e7d02e3b485dbe0f241c9d9e3283bd8f59074be5feed9df908961

test:
  secret_key_base: c79881ce7e84a6234cddff2275ec85bae2d4d86d84a5b5f3891b7dfaeec67b9c79a12e580a8aa6da551032a4cac9bfc10b806c0cfb3ec1aa3da69aabc1b40851

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
